gringo/urls.py
from django.contrib import admin
from django.urls import path
from stock import views
from django.conf.urls import include, url

urlpatterns = [
	path('campaña/nueva', views.CampañaCreate.as_view(), name='campaña_nueva'),
    path('admin/', admin.site.urls),
    # Other URL patterns ...
    url(r'^accounts/', include('django_registration.backends.activation.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    path('_db', views.download_db),
	path('stock/', views.stock, name = 'resumen_stock'),
	path('', views.inicio, name='inicio'),
    path('campañas/', views.campañas_listado, name = 'resumen_campañas'),
	path('campaña/<int:id>', views.campaña_detalle, name='campaña_detalle'),
    path('campaña/<int:id>/nueva_actividad', views.ActividadCreate.as_view(), name='nueva_actividad'),
    path('campaña/<int:id_campaña>/actividad/<int:id_actividad>', views.actividad_detalle, name='actividad_detalle'),
    path('movimientos/', views.mov_gral, name='resumen_movimientos'),
    path('lotes/', views.mov_gral, name='resumen_lotes'),
    path('lote/nuevo', views.LoteCreate.as_view(), name="Lote_Nuevo"),
    path('actividades/', views.actividades, name='resumen_actividades')
]

stock/models.py
from django.db import models
from django.urls import reverse
from model_utils import Choices
from model_utils.models import TimeStampedModel


# Create your models here.

class Cultivo(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Campaña(models.Model):
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    fecha_creacion =  models.DateTimeField(auto_now_add=True)
    nombre = models.CharField(max_length=50, verbose_name='Nombre de la campaña', help_text='Ejemplo: Soja Primavera 2018')
    cultivo = models.ForeignKey('Cultivo', on_delete=models.SET_NULL, blank=True, null=True)
    lote = models.ForeignKey('Lote', on_delete=models.SET_NULL, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('campaña_detalle', args=[self.id])

    def __str__(self):
        return self.nombre


class Lote(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(null=True, blank=True)
    latitud = models.FloatField(null=True, blank=True)
    longitud = models.FloatField(null=True, blank=True)
    hectareas = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.nombre



class TipoActividad(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Tipo de actividad'
        verbose_name_plural = "Tipo de actividades"


class Actividad(TimeStampedModel):
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField(null=True, blank=True)
    campaña = models.ForeignKey('Campaña', on_delete=models.CASCADE)
    tipo = models.ForeignKey('TipoActividad', on_delete=models.SET_NULL, blank=True, null=True)
    descripcion = models.TextField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse(
            'actividad_detalle',
            kwargs=dict(
                id_campaña=self.campaña.id,
                id_actividad=self.id
            )
        )

    def __str__(self):
        return self.descripcion


    class Meta:
        verbose_name_plural = "actividades"


class CategoriaProducto(models.Model):
    nombre = models.CharField(max_length=50, help_text='Ej: Semilla, fertilizante, herbicida, etc')

    def __str__(self):
        return self.nombre


class UnidadMedida(models.Model):
    nombre = models.CharField(max_length=50, help_text='Ej: Bidon x 20l, Hora, etc')


    def __str__(self):
        return self.nombre


class Producto(TimeStampedModel):
    """
    Este es la tabla que describe insumo o producidho o servicios con su precio actual
    """
    nombre = models.CharField(max_length=50)
    categoria = models.ForeignKey('CategoriaProducto', null=True, on_delete=models.SET_NULL)
    unidad_medida = models.ForeignKey('UnidadMedida', null=True, on_delete=models.SET_NULL)
    precio_peso = models.DecimalField(max_digits=12, decimal_places=3)
    precio_dolar = models.DecimalField(max_digits=12, decimal_places=3)

    def __str__(self):
        return f'{self.nombre} x {self.unidad_medida}'


class TipoMovimiento(models.Model):
    tipo = models.CharField(max_length=50, help_text='Ej: compra, venta')
    aumenta = models.BooleanField(default=True)

    def __str__(self):
        'Muestra el nombre del objeto'
        return self.tipo


class Movimiento(TimeStampedModel):
    OPC_TC = Choices(('001', 'Factura A'), ('004', 'Recibos A'),
                     ('006', 'Factura B'), ('009', 'Recibos B'),
                     ('011', 'Factura C'), ('015', 'Recibos C'),
                     ('017', 'Liq.Serv.Publ.A'), ('018', 'Liq.Serv.Publ.B'),
                     ('033', 'Liq.Prim.de Granos'), ('089', 'Resumen de datos')
                    )
    OPC_LETRA = Choices('A', 'B', 'C', 'M', 'E', 'X')

    producto    = models.ForeignKey('Producto', on_delete=models.CASCADE)
    tipo        = models.ForeignKey('TipoMovimiento', on_delete=models.CASCADE)
    cantidad    = models.DecimalField(max_digits=12, decimal_places=3)
    descripcion = models.TextField(null=True, blank=True)
    fecha       = models.DateTimeField()
    es_inicial  = models.BooleanField(default=False, help_text='Calcular stock a partir de esta cantidad')
    actividad   = models.ForeignKey('Actividad', on_delete=models.CASCADE)
    precio_peso = models.DecimalField(max_digits=12, decimal_places=3)
    precio_dolar= models.DecimalField(max_digits=12, decimal_places=3)
    tipo_comp   = models.CharField(choices=OPC_TC, default='OPC_TC.089', max_length=3, verbose_name='Tipo de comprobante')
    letra_comp  = models.CharField(choices=OPC_LETRA, default=OPC_LETRA.X, max_length=1, verbose_name='Letra')
    pto_venta   = models.IntegerField(verbose_name='Punto de venta')
    nro_comp    = models.IntegerField(verbose_name='Número de comprobante')

    def __str__(self):
        return f'{self.tipo}: {self.producto} ({self.cantidad} {self.producto.unidad_medida})'


    def save(self, *args, **kwargs):
        """Sobrecarga del metodo que se encarga de guardar el estado
        actual de la instancia Movimiento (a nivel python) a la
        base de datos.

        Antes de efectivamente guardar, calculamos si el valor cantidad debe
        ser positivo o negativo en funcion del tipo de movimiento
        """
        if not self.tipo.aumenta:
            self.cantidad = - abs(self.cantidad)
        else:
            self.cantidad = abs(self.cantidad)
        super().save(*args, **kwargs)

stock/forms.py
#https://docs.djangoproject.com/en/2.1/topics/forms/
# https://tutorial.djangogirls.org/es/django_forms/
from django import forms
from .models import Movimiento, Lote, Campaña, Cultivo
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field

class FilterForm(forms.ModelForm):
    actividad__campaña = forms.ModelChoiceField(label="Campaña",
                                                empty_label="Elegir campaña",
                                                queryset=Campaña.objects.all())
    actividad__campaña__lote = forms.ModelChoiceField(label="Lote",
                                                      empty_label="Elegir Lote",
                                                      queryset=Lote.objects.all())
    actividad__campaña__cultivo = forms.ModelChoiceField(label="Cultivo",
                                                         empty_label="Elegir cultivo",
                                                         queryset=Cultivo.objects.all())

    orden = forms.ChoiceField(choices=[
        ('producto', 'Producto (asc)'),
        ('-producto', 'Producto (desc)'),
        ('tipo', 'Tipo (asc)'),
        ('-tipo', 'Tipo (desc)'),
         ('actividad', 'Actividad (asc)'),
        ('-actividad', 'Actividad (desc)')
    ])

    class Meta:
        model =  Movimiento
        fields = ('producto', 'tipo',  'actividad', 'actividad__campaña__lote',
        'actividad__campaña', 'actividad__campaña__cultivo',
        'tipo_comp', 'letra_comp','pto_venta','nro_comp')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'id-form'
        self.helper.form_method = 'get'

        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-form-label-sm'
        self.helper.field_class = 'col'

        self.helper.layout = Layout(
            Field(*self.fields, css_class='custom-select custom-select-sm',
            onchange='document.forms["id-form"].submit();')
        )

        self.fields['producto'].empty_label = "Elegir producto"
        self.fields['tipo'].empty_label = "Elegir tipo"
        self.fields['actividad'].empty_label = "Elegir actividad"
        self.fields['tipo_comp'].empty_label = "Elegir Tipo de comprobante "
        self.fields['letra_comp'].empty_label = "Elegir Letra"

        # self.helper.add_input(Submit('submit-button', 'Filtrar'))

        self.helper.add_input(Submit('submit-button', 'Filtrar', css_class='btn btn-primary btn-shadow btn-gradient'))

        #self.tipo_comp(default)  ## resetea valor para que no aplique filtro no deseado.
        #self.letra(default)  ## resetea valor para que no aplique filtro no deseado.

        for key in self.fields:
            self.fields[key].required = False
        self.fields['tipo_comp'].choices = [('', '---')] + Movimiento.OPC_TC
        self.fields['tipo_comp'].required = False
        self.fields['letra_comp'].choices = [('', '---')] + Movimiento.OPC_LETRA
        self.fields['letra_comp'].required = False


class MovimientoModelForm(forms.ModelForm):
    class Meta:
        model = Movimiento
        fields = [
            'producto', 'tipo', 'cantidad', 'descripcion',
            'fecha', 'es_inicial', 'precio_peso',
            'precio_dolar', 'tipo_comp', 'letra_comp', 'pto_venta',
            'nro_comp'
        ]

stock/views.py
import os

from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Sum
from django.http import HttpResponseForbidden
from wsgiref.util import FileWrapper
from django.http import HttpResponse
from django.conf import settings
from .models import Movimiento, Producto, Campaña, CategoriaProducto,Lote
from .models import Movimiento, Producto, Actividad, Movimiento, Campaña, CategoriaProducto
from .forms import FilterForm, MovimientoModelForm
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin


class CampañaCreate(LoginRequiredMixin, CreateView):
    model = Campaña
    fields = ['nombre', 'cultivo', 'lote']

    def form_valid(self, form):
        campaña = form.save(commit=False)
        campaña.usuario = self.request.user
        campaña.save()
        return redirect('/')

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        opciones_lote = form.fields['lote'].queryset
        # limitamos las opciones de lote a los lotes que pertenezcan al usuario 
        # logueado. Por defecto, asume que son todas, y lo filtramos 
        # con self.request.user
        form.fields['lote'].queryset = opciones_lote.filter(usuario=self.request.user)
        return form


class LoteCreate(LoginRequiredMixin, CreateView):
    model = Lote
    fields = ['nombre', 'descripcion', 'latitud', 'longitud', 'hectareas']

    def form_valid(self, form):
        lote = form.save(commit=False)
        lote.usuario = self.request.user
        lote.save()
        return redirect('/')


@login_required
def campaña_detalle(request, id):
    campaña = get_object_or_404(Campaña, id=id, usuario=request.user)
    return render(request, 'stock/campaña_detalle.html', {'campaña': campaña})


class ActividadCreate(LoginRequiredMixin, CreateView):
    model = Actividad
    fields = ['fecha_inicio', 'fecha_fin', 'tipo', 'descripcion']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['campaña'] = get_object_or_404(Campaña, id=self.kwargs['id'])
        return context

    def form_valid(self, form):
        actividad = form.save(commit=False)
        actividad.campaña = get_object_or_404(Campaña, id=self.kwargs['id'])
        actividad.save()
        return redirect(actividad)


@login_required
def actividad_detalle(request, id_campaña, id_actividad):
    campaña = get_object_or_404(Campaña, id=id_campaña)
    if campaña.usuario != request.user:
        return HttpResponseForbidden()
    actividad = get_object_or_404(Actividad, campaña=campaña, id=id_actividad)
    form = MovimientoModelForm(request.POST if request.method == 'POST' else None)
    if form.is_valid():
        mov = form.save(commit=False)
        mov.actividad = actividad
        mov.save()
        return redirect(actividad)

    return render(request, 'stock/actividad_detalle.html', {
        'campaña': campaña,
        'actividad': actividad,
        'form': form,
    })


@login_required
def stock(request):
    tabla = {}
    for p in Producto.objects.all():
        # buscamos el movimiento inicial mas nuevo, o el primero que exista
        inicial = p.movimiento_set.filter(
            es_inicial=True
        ).order_by('-fecha').first() or p.movimiento_set.order_by('fecha').first()

        if not inicial:
            # si no hay movimientos, el stock para este producto es 0
            tabla[p] = 0
            continue

        # filtramos todos los movimientos asociados al producto posteriores al inicial
        contables = p.movimiento_set.filter(fecha__gte=inicial.fecha)
        # sumamos  cantidades a partir del movimiento incial
        total = contables.aggregate(total=Sum('cantidad'))['total']
        tabla[p] = total
    return render(request, 'stock/stock.html', {'tabla': tabla})


@login_required
def campañas_listado(request):
    tabla = {}
    # sólo listar campañas propias
    for cmp in Campaña.objects.filter(usuario=request.user):
        # Datos de la campaña...
        # calcular cantidad*precio_peso, cantidad*precio_dolar
        total = Movimiento.objects.filter(
            actividad__campaña=cmp
        ).aggregate(total_pesos=Sum('precio_peso'),
                    total_dolares=Sum('precio_dolar'))
        tabla[cmp] = total
    return render(request, 'stock/campañas_listado.html', {'tabla': tabla})


@login_required
def lote(request):
    tabla = {}
    for cmp in Lote.objects.all():
        # Datos de la campaña...
        # calcular cantidad*precio_peso, cantidad*precio_dolar
        total = Movimiento.objects.filter(
            actividad__campaña=cmp
        ).aggregate(total_pesos=Sum('precio_peso'),
                    total_dolares=Sum('precio_dolar'))
        tabla[cmp] = total
    return render(request, 'stock/campañas.html', {'tabla': tabla})



@login_required
def mov_gral (request):
    tabla = Movimiento.objects.all()
    if request.method == 'GET':
        formfilter = FilterForm(request.GET)

    if formfilter.is_valid():
        orden = formfilter.cleaned_data.pop('orden')
        for clave, valor in formfilter.cleaned_data.items(): #recorre las opciones de filtrado.
            # si el formulario de filtro es valido (por ahora cualquier configuracion lo es)
            # entonces los "datos enviados y limpios" se iteran para aplicarlos iterativamente
            # como filtros.
            # Para esto se usa el "desempacado de parametros" (**kwargs)
            # que es una forma de pasar parametros nombrados a partir de un diccionario

            if not valor:   # filtra cada opcion seleccionada.
                continue
            tabla = tabla.filter(**{clave: valor}) # Los ** convierten el dicc a un string con sus valores corresp.
    else:
        formfilter = FilterForm()
    if orden:
        tabla = tabla.order_by(orden)

    return render(request, 'stock/mov_gral.html', {'form': formfilter, 'object_list': tabla})


def inicio(request):
    '''if request.user.is_authenticated:
        # si el usuario ya está logueado, no le mostramos el landing page
        return redirect('resumen_campañas')'''
    return render(request, 'stock/landing.html')


@login_required
def actividades(request):
    return render(request, 'stock/actividades.html')


@login_required
def download_db(request):
    filename = settings.DATABASES['default']['NAME']
    response = HttpResponse(open(filename, 'rb').read(), content_type='application/x-sqlite3')
    response['Content-Disposition'] = 'attachment; filename=%s' % os.path.basename(filename)
    response['Content-Length'] = os.path.getsize(filename)
    return response

stock/templates/stock/actividad_detalle.html
{% extends 'stock/campaña_detalle.html' %}
{% load bootstrap4 %}

{% block content %}


<div class="container-fluid">
    <div class="row">
        <div class="col-12">
           <h1>
             Actividad en «<a href="{%url 'campaña_detalle' campaña.id %}" >{{ campaña }}</a>»
           </h1>

           <dl>
              <dt>Tipo</dt>
              <dd>{{ actividad.tipo }}</dd>
              <dt>Fecha de inicio: </dt>
              <dd> {{ actividad.fecha_inicio|date }}</dd>
              <dt>Fecha de finalización: </dt>
              <dd> {{ actividad.fecha_fin|date }}</dd>

           </dl>


  <div class="row">
    <div class="col-md-6">
        <h3>Movimientos</h3>


        <ul class="list-unstyled">
        {% for movimiento in actividad.movimiento_set.all %}

        <li class="media g-mb-30 media-comment">
          {% comment %}
             <img class="mr-3" src="..." alt="Generic placeholder image">
           {% endcomment %} <div class="media-body shadow p-3 mb-5 bg-white rounded">
            <h5 class="mt-0 mb-1">{{ actividad.nombre }}</h5>
            <dl>
              <dt>Tipo</dt>
              <dd>{{ movimiento.tipo }}</dd>
              <dt>Fecha</dt>
              <dd>{{ movimiento.fecha|date }}</dd>
              <dt>Monto en $</dt>
              <dd>{{ movimiento.precio_peso }}</dd>
              <dt>Monto en u$s</dt>
              <dd>{{ movimiento.precio_dolar }}</dd>
              <dt>Detalle</dt>
              <dd>{{ movimiento.detalle }}</dd>
            </dl>

          </div>
        </li>
        {% endfor %}
        </ul>
    </div>

    <div class="col-md-6">
      <h3>Nuevo</h3>
       <form method="POST" >
            {% csrf_token %}
    {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="save btn btn-default">
            {% block submit_text %}
                Guardar
            {% endblock %}</button>
        {% endbuttons %}

        </form>
    </div>


  </div>


        </div>
    </div>

{% endblock %}

stock/templates/stock/actividad_form.html
{% extends 'stock/form.html' %}

{% block titulo %}
    Nueva actividad en «{{ campaña }}»
{% endblock titulo %}

{% block submit_text %}Guardar{% endblock %}

stock/templates/stock/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Gringo: gestioná tu campo</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static "vendor/font-awesome/css/font-awesome.min.css" %}">
    <!-- Custom Font Icons CSS-->
    <link rel="stylesheet" href="{% static "css/landy-iconfont.css" %}">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="{% static "https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" %}">
    <!-- owl carousel-->
    <link rel="stylesheet" href="{% static "vendor/owl.carousel/assets/owl.carousel.css" %}">
    <link rel="stylesheet" href="{% static "vendor/owl.carousel/assets/owl.theme.default.css" %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static "css/style.green.css" id="theme-stylesheet" %}">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static "css/custom.css" %}">
    <!-- Favicon-->        </div>

    <link rel="shortcut icon" href="{% static "favicon.png" %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
<body>
    <header class="header">
        <nav class="navbar navbar-expand-lg fixed-top"><a href='{% url 'inicio'%}' class="navbar-brand">Gringo</a>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">
            {% block nav %}
            {% endblock %}
            </div>

            {% if request.user.is_authenticated %}

            <div class="navbar-text justify-content-left">
                <ul class="navbar-nav align-items-start align-items-lg-center">
                    <li class="nav-item"><a class="nav-link" href="{% url 'resumen_campañas'%}">CAMPAÑAS</a></li>
                    <!--li class="nav-item"><a class="nav-link" href="{% url 'resumen_lotes'%}">LOTES</a></li-->
                    <li class="nav-item"><a class="nav-link" href='{% url 'resumen_stock' %}'>STOCK</a></li>

                    <li class="nav-item"><a class="nav-link disable" href="{% url 'resumen_movimientos'%}">REPORTES</a></li>
                </ul>
            </div>
                    <div class="navbar-text">
                      <!-- Button trigger modal--><a href="/accounts/logout/" class="btn btn-primary navbar-btn btn-shadow btn-gradient">Cerrar Sesión</a>
                    </div>
            {% else %}
                    <div class="navbar-text mr-2">
                      <a href="/accounts/login/" class="btn btn-primary navbar-btn btn-shadow btn-gradient">Iniciar Sesión</a>
                    </div>
                    <div class="navbar-text">
                      <a href="/accounts/register/" class="btn btn-outline-primary">Registrate</a>
                    </div>
            {% endif %}
        </nav>
    </header>

    <section {% block content_class%}id="hero" class="hero hero-home bg-gray{% endblock %}">
        {% block content%}
        {% endblock %}
    </section>


    <footer class="main-footer">
      <div class="container">
        <div class="row">
          <div class="text-center col-lg-12 col-md-12 offset-lg-12 offset-md-12"><a href="#" class="brand">Contacto</a>
            <ul class="contact-info list-unstyled">
              <li><a href="atencionclientes@gringo.com.ar">atencionclientes@gringo.com.ar</a></li>
              <li><a href="tel:3516564342">+54 9 351 6564342</a></li>
            </ul>
            <ul class="social-icons list-inline">
              <li class="list-inline-item"><a href="#" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
              <li class="list-inline-item"><a href="#" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href="#" target="_blank" title="Instagram"><i class="fa fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href="#" target="_blank" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
             </ul>
          </div>
          {% comment %} <div class="col-lg-3 col-md-6">
            <h5>Selected Cases</h5>
            <ul class="links list-unstyled">
              <li> <a href="#">Guess Conntect</a></li>
              <li> <a href="#">Postly</a></li>
              <li> <a href="#">Iris Vor Arnim</a></li>
              <li> <a href="#">Yapital</a></li>
            </ul>
          </div>
          <div class="col-lg-3 col-md-6">
            <h5>Selected Cases</h5>
            <ul class="links list-unstyled">
              <li> <a href="#">Guess Conntect</a></li>
              <li> <a href="#">Postly</a></li>
              <li> <a href="#">Iris Vor Arnim</a></li>
              <li> <a href="#">Yapital</a></li>
            </ul>
          </div>
          <div class="col-lg-3 col-md-6">
            <h5>Selected Cases</h5>
            <ul class="links list-unstyled">
              <li> <a href="#">Guess Conntect</a></li>
              <li> <a href="#">Postly</a></li>
              <li> <a href="#">Iris Vor Arnim</a></li>
              <li> <a href="#">Yapital</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="copyrights">
        <div class="container">
          <div class="row">
            <div class="text-center col-lg-6 col-md-6 offset-lg-6 offset-md-6">
             <p>&copy; 2018 gringo.com Todos los derechos reservados</p>
            </div>
            <div class="col-md-5 text-right">
              <p>Template By <a href="https://bootstrapious.com/" class="external">Bootstrapious</a>  </p>
              <!-- Please do not remove the backlink to Bootstrapious unless you support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :) -->
            </div>
          </div>
        </div>{% endcomment %}
      </div>
    </footer>
    <!-- Javascript files-->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"> </script>
    <script src="{% static "jquery.cookie/jquery.cookie.js" %}"> </script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/front.js" %}"></script>
    <script src="{% static "owl.carousel/owl.carousel.min.js" %}"></script>

  </body>
</html>

stock/templates/stock/bootstrap.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% block bootstrap4_title %}{% block title %}{% endblock %}{% endblock %}

stock/templates/stock/campaña_detalle.html
{% extends 'stock/base.html' %}
{% load bootstrap4 %}

{% block base_class %}starter-template{% endblock %}


{% block content %}


<div class="container-fluid">
    <h2> Campaña «{{ campaña.nombre }}» </h2>
    <div class="row">
        <div class="col-12">

           <dl>
             <dt>Cultivo: </dt>
             <dd> {{ campaña.cultivo }}</dd>
             <dt>Fecha de inicio: </dt>
             <dd> {{ campaña.fecha_creacion|date }}</dd>
             <dt>Lote: </dt>
             <dd> {{ campaña.lote }}</dd>
           </dl>



<div class="row">
    <div class="col-md-6">
        <h3>Actividades</h3>

        <small class="d-block text-right mt-3 mb-3">
          <a class="btn btn-primary navbar-btn btn-shadow btn-gradient" href="{% url 'nueva_actividad' campaña.id %}">Nueva actividad</a>
        </small>

        <ul class="list-unstyled">
        {% for actividad in campaña.actividad_set.all %}

        <li class="media g-mb-30 media-comment">
          {% comment %}
             <img class="mr-3" src="..." alt="Generic placeholder image">
           {% endcomment %} <div class="media-body shadow p-3 mb-5 bg-white rounded">
            <h5 class="mt-0 mb-1">{{ actividad.nombre }}</h5>
            <p>{{ actividad.descripcion}}</p>
            <dl>
              <dt>Tipo</dt>
              <dd>{{ actividad.tipo }}</dd>
              <dt>Fecha de inicio: </dt>
              <dd> {{ actividad.fecha_inicio|date }}</dd>
              <dt>Fecha de finalización: </dt>
              <dd> {{ actividad.fecha_fin|date }}</dd>
            </dl>


          <small class="d-block text-right mt-3 mb-1">
            <a class="btn btn-primary navbar-btn btn-shadow btn-gradient" href="{% url 'actividad_detalle' campaña.id actividad.id %}">Ver Detalle</a>
          </small>

          </div>
        </li>
        {% endfor %}
        </ul>
    </div>
    </div>


        </div>
    </div>

{% endblock %}

stock/templates/stock/lote_form.html
{% extends 'stock/form.html' %}

{% block submit_text %}Guardar{% endblock %}